kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: anthos-sample-cluster2
  labels:
    ifa: primary
---
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: anthos-sample-cluster3
  labels:
    ifa: secondary
