apiVersion: v1
kind: Service
metadata:
  name: helloweb-lb
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP