apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
    name: config-management
    namespace: config-management-system
spec:
  clusterName: <CLUSTER_NAME>
  git:
    syncRepo: <REPO_URL>
    syncBranch: master
    secretType: gcenode
    policyDir: "."
    syncWait: 2
  policyController:
    enabled: true
