apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: gemma-gozaru
spec:
  modelName: tarota0226/gemma-gozaru-adapter   # LoRA
  criticality: Standard
  poolRef:
    name: gozaru-gemma-pool
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: gemma-base
spec:
  modelName: google/gemma-3-4b-it             # ベース
  criticality: Critical
  poolRef:
    name: gozaru-gemma-pool
