apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: frontend-route
spec:
  parentRefs:
  - name: external-http
  hostnames:
  - "x-x-x-x.nip.io"
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: frontend
      port: 80
