deployment.yaml:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-dojo
spec:
  selector:
    matchLabels:
      app: gke-dojo
  template:
    metadata:
      labels:
        app: gke-dojo
    spec:
      containers:
      - name: gke-dojo
        image: gke-dojo
        ports:
          - containerPort: 8000