apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: disable-vm-external-ip
  namespace: policies
spec:
  constraint: "constraints/compute.vmExternalIpAccess"
  listPolicy:
    deny:
      all: true
  organizationRef:
    external: "123456789012" # kpt-set: ${org-id}
