steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gig02-app:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gig02-app:$BUILD_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    '--image=gcr.io/$PROJECT_ID/gig02-app:$BUILD_ID',
    '--service-account=dev-gig-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--platform=managed',
    '--region=us-central1',
    '--allow-unauthenticated',
    '--set-env-vars',
    'GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
    'gig02-app',
  ]