runtime: go112

handlers:
  - url: /.*
    secure: always
    script: auto

vpc_access_connector:
  name: "projects/your-project-id/locations/us-central1/connectors/gig-vpc-connector"

env_variables:
  REDIS_HOST: 0.0.0.0
  REDIS_PORT: 6379
  
