---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: gke-dojo
description: gke-dojo 
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/PROJECT_ID/locations/asia-northeast1/clusters/gke-dojo-cluster
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/PROJECT_ID/locations/asia-northeast1/clusters/gke-dojo-cluster-prod