apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: qwen-objective
  namespace: default
spec:
  priority: 10
  poolRef:
    name: qwen-pool
    group: "inference.networking.k8s.io"
