apiVersion: v1
kind: Namespace
metadata:
  name: keda-pubsub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-pubsub-sa
  namespace: keda-pubsub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-pubsub
  namespace: keda-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-pubsub
  template:
    metadata:
      labels:
        app: keda-pubsub
    spec:
      serviceAccountName: keda-pubsub-sa
      containers:
      - name: subscriber
        image: us-docker.pkg.dev/google-samples/containers/gke/pubsub-sample:latest
        env:
        - name: PROJECT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['project-id']
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
