apiVersion: v1
kind: Namespace
metadata:
  name: keda-pubsub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-pubsub-sa
  namespace: keda-pubsub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-pubsub
  namespace: keda-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-pubsub
  template:
    metadata:
      labels:
        app: keda-pubsub
    spec:
      serviceAccountName: keda-pubsub-sa
      containers:
      - name: subscriber
        image: asia-northeast1-docker.pkg.dev/gke-handson-sample/gke-dojo/keda-pubsub-worker:v1
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
