apiVersion: v1
kind: Service
metadata:
  name: gemma3-1b-lora-service
spec:
  type: LoadBalancer
  selector:
    app: gemma3-1b-lora-server # deployment.yamlのラベルと一致
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080