name: "tftrt_fp16_bs8_count4"
platform: "tensorflow_savedmodel"
max_batch_size: 8
input {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 224, 224, 3 ]
}
output {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: 1000
    label_filename: "imagenet1k_labels.txt"
}
default_model_filename: "model"
instance_group [
    {
        count: 4
        kind: KIND_GPU
    }
]
dynamic_batching {
    preferred_batch_size: [ 8 ]
    max_queue_delay_microseconds: 20000
}
