steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/egg1-app:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/egg1-app:$BUILD_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    '--image=gcr.io/$PROJECT_ID/egg1-app:$BUILD_ID',
    '--service-account=dev-egg-sa@$PROJECT_ID.iam.gserviceaccount.com',
    '--platform=managed',
    '--region=us-central1',
    '--allow-unauthenticated',
    'egg1-app',
  ]
