steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-lab-jp/devops-handson:$SHORT_SHA",
        ".",
      ]
    dir: "devops/"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcp-getting-started-lab-jp/devops-handson:$SHORT_SHA",
      ]
