
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-slave
  labels:
    name: locust-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-slave
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      containers:
      - name: locust-slave
        image: gcr.io/sandbox-kathryn-ml/locust_tester
        command: ["locust","-f","locust/trtis_grpc_client.py"]
        args: ["--slave", "--master-host=CLUSTER_IP_LOCUST_MASTER"]
        resources:
          requests:
            cpu: 100m
