apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"gke-ingress-config"}}'
    configmanagement.gke.io/cluster-selector: ifa
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-mcsingressgw
spec:
  template:
    spec:
      ports:
      - name: http2
        port: 80
        targetPort: 80
      - name: https
        port: 443
      - name: tls
        port: 15443
        targetPort: 15443
      - name: tcp
        port: 31400
      selector:
        app: istio-ingressgateway
        istio: ingressgateway
